import type { ModelCapability } from "./types";

export const STARTER_RUNWARE_CATALOG: readonly ModelCapability[] = [
 {id:"heis-text-standard",provider:"runware",providerModelId:"openai:gpt@5.4-mini",displayName:"Heis Text Standard",operation:"generate-text",outputKind:"other",maximumEstimatedCostUsd:.5,enabled:true,parameters:[{name:"prompt",type:"string",required:true}]},
  {
    id: "heis-highlight-analysis", provider: "runware", providerModelId: "openai:gpt@5.4-mini",
    displayName: "AI highlight analysis", operation: "rank-highlights", outputKind: "other",
    maximumEstimatedCostUsd: 0.50, enabled: true,
    parameters: [
      { name: "transcript", type: "object", required: true },
      { name: "count", type: "number", minimum: 1, maximum: 10, required: true },
      { name: "minDuration", type: "number", minimum: 5, maximum: 180, required: true },
      { name: "maxDuration", type: "number", minimum: 5, maximum: 180, required: true },
    ],
  },
  {
    id: "heis-image-layers",
    provider: "runware",
    providerModelId: "alibaba:qwen-image@layered",
    displayName: "Qwen Image Layers",
    operation: "decompose-layers",
    outputKind: "image",
    maximumEstimatedCostUsd: 0.30,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "object", required: true },
      { name: "settings", type: "object", required: true },
      { name: "outputFormat", type: "enum", options: ["TIFF"], required: true },
    ],
  },
  {
    id: "heis-image-standard",
    provider: "runware",
    providerModelId: "runware:101@1",
    displayName: "Heis Image Standard",
    operation: "text-to-image",
    outputKind: "image",
    maximumEstimatedCostUsd: 0.15,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "width", type: "number", default: 1024, minimum: 256, maximum: 2048 },
      { name: "height", type: "number", default: 1024, minimum: 256, maximum: 2048 },
    ],
  },
  {
    id: "heis-image-edit-standard",
    provider: "runware",
    providerModelId: "runware:101@1",
    displayName: "Heis Image Edit Standard",
    operation: "image-to-image",
    outputKind: "image",
    maximumEstimatedCostUsd: 0.18,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "seedImage", type: "media", required: true },
      { name: "strength", type: "number", default: 0.8, minimum: 0, maximum: 1 },
    ],
  },
  {
    id: "heis-image-upscale",
    provider: "runware",
    providerModelId: "topazlabs:wonder@3.5",
    displayName: "Heis Image Upscale",
    operation: "upscale",
    outputKind: "image",
    maximumEstimatedCostUsd: 0.6,
    enabled: true,
    parameters: [
      { name: "inputs", type: "object", required: true },
      { name: "upscaleFactor", type: "number", default: 2, minimum: 2, maximum: 6 },
      { name: "settings", type: "object" },
    ],
  },
  {
    id: "heis-remove-background",
    provider: "runware",
    providerModelId: "runware:109@1",
    displayName: "Heis Background Removal",
    operation: "remove-background",
    outputKind: "image",
    maximumEstimatedCostUsd: 0.01,
    enabled: true,
    parameters: [
      { name: "inputs", type: "object", required: true },
      { name: "outputFormat", type: "enum", default: "PNG", options: ["PNG"] },
      { name: "settings", type: "object" },
    ],
  },
  {
    id: "heis-expand-image",
    provider: "runware",
    providerModelId: "bfl:flux@outpainting",
    displayName: "Heis Image Expansion",
    operation: "expand-image",
    outputKind: "image",
    maximumEstimatedCostUsd: 0.5,
    enabled: true,
    parameters: [
      { name: "inputs", type: "object", required: true },
      { name: "outpaint", type: "object", required: true },
      { name: "settings", type: "object" },
    ],
  },
  {
    id: "heis-video-text-standard",
    provider: "runware",
    providerModelId: "google:3@3",
    displayName: "Heis Text to Video Standard",
    operation: "text-to-video",
    outputKind: "video",
    maximumEstimatedCostUsd: 5,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "duration", type: "number", default: 5, minimum: 4, maximum: 10 },
      { name: "aspectRatio", type: "enum", default: "16:9", options: ["16:9", "9:16", "1:1"] },
    ],
  },
  {
    id: "heis-video-standard",
    provider: "runware",
    providerModelId: "runway:1@1",
    displayName: "Heis Video Standard",
    operation: "image-to-video",
    outputKind: "video",
    maximumEstimatedCostUsd: 1.5,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "media", required: true },
      { name: "duration", type: "number", default: 5, minimum: 5, maximum: 10 },
    ],
  },
  {
    id: "heis-video-transform",
    provider: "runware",
    providerModelId: "luma:ray@3.2",
    displayName: "Heis Video Transform",
    operation: "video-to-video",
    outputKind: "video",
    maximumEstimatedCostUsd: 2,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "media", required: true },
      { name: "resolution", type: "enum", default: "720p", options: ["720p"] },
    ],
  },
  {
    id: "heis-marketing-video",
    provider: "runware",
    providerModelId: "alibaba:wan@3.0",
    displayName: "Heis Marketing Video",
    operation: "reference-to-video",
    outputKind: "video",
    maximumEstimatedCostUsd: 3,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "object", required: true },
      { name: "width", type: "number", required: true },
      { name: "height", type: "number", required: true },
      { name: "duration", type: "number", default: 5, minimum: 4, maximum: 15 },
    ],
  },
  {
    id: "heis-motion-control",
    provider: "runware",
    providerModelId: "bytedance:seedance@2.5",
    displayName: "Heis Motion Control",
    operation: "motion-control",
    outputKind: "video",
    maximumEstimatedCostUsd: 9,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "object", required: true },
      { name: "duration", type: "number", default: 5, minimum: 4, maximum: 30 },
      { name: "settings", type: "object" },
      { name: "seed", type: "number" },
    ],
  },
  {
    id: "heis-recast",
    provider: "runware",
    providerModelId: "bytedance:seedance@2.5",
    displayName: "Heis Recast",
    operation: "motion-control",
    outputKind: "video",
    maximumEstimatedCostUsd: 9,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "object", required: true },
      { name: "duration", type: "enum", default: "auto", options: ["auto"] },
      { name: "settings", type: "object" },
    ],
  },
  {
    id: "heis-motion-graphics",
    provider: "runware",
    providerModelId: "bytedance:seedance@2.5",
    displayName: "Heis Motion Graphics",
    operation: "text-to-video",
    outputKind: "video",
    maximumEstimatedCostUsd: 7,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "width", type: "number", required: true },
      { name: "height", type: "number", required: true },
      { name: "duration", type: "number", default: 6, minimum: 4, maximum: 30 },
      { name: "settings", type: "object" },
    ],
  },
  {
    id: "heis-motion-graphics-edit",
    provider: "runware",
    providerModelId: "bytedance:seedance@2.5",
    displayName: "Heis Motion Graphics Remix",
    operation: "video-to-video",
    outputKind: "video",
    maximumEstimatedCostUsd: 9,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "object", required: true },
      { name: "duration", type: "enum", default: "auto", options: ["auto"] },
      { name: "resolution", type: "enum", default: "720p", options: ["720p"] },
      { name: "settings", type: "object", required: true },
    ],
  },
  {
    id: "heis-lipsync-video",
    provider: "runware",
    providerModelId: "sync:lipsync-2@1",
    displayName: "Heis Video Lip Sync",
    operation: "lip-sync",
    outputKind: "video",
    maximumEstimatedCostUsd: 5,
    enabled: true,
    parameters: [
      { name: "inputs", type: "object", required: true },
      { name: "providerSettings", type: "object", required: true },
    ],
  },
  {
    id: "heis-lipsync-image",
    provider: "runware",
    providerModelId: "creatify:aurora@fast",
    displayName: "Heis Portrait Lip Sync",
    operation: "lip-sync",
    outputKind: "video",
    maximumEstimatedCostUsd: 2,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string" },
      { name: "inputs", type: "object", required: true },
    ],
  },
  {
    id: "heis-speech-standard",
    provider: "runware",
    providerModelId: "minimax:speech@2.8",
    displayName: "Heis Speech Standard",
    operation: "text-to-speech",
    outputKind: "audio",
    maximumEstimatedCostUsd: 2,
    enabled: true,
    parameters: [
      { name: "speech", type: "object", required: true },
    ],
  },
  {
    id: "heis-music-standard",
    provider: "runware",
    providerModelId: "minimax:music@2.6",
    displayName: "Heis Music Standard",
    operation: "text-to-music",
    outputKind: "audio",
    maximumEstimatedCostUsd: 0.5,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "settings", type: "object" },
    ],
  },
];

export function getCapability(id: string): ModelCapability | undefined {
  return STARTER_RUNWARE_CATALOG.find((capability) => capability.id === id);
}
