import type { ModelCapability } from "./types";

export const STARTER_RUNWARE_CATALOG: readonly ModelCapability[] = [
  {
    id: "heis-image-standard",
    provider: "runware",
    providerModelId: "runware:101@1",
    displayName: "Heis Image Standard",
    operation: "text-to-image",
    outputKind: "image",
    maximumEstimatedCostUsd: 0.15,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "width", type: "number", default: 1024, minimum: 256, maximum: 2048 },
      { name: "height", type: "number", default: 1024, minimum: 256, maximum: 2048 },
    ],
  },
  {
    id: "heis-image-edit-standard",
    provider: "runware",
    providerModelId: "runware:101@1",
    displayName: "Heis Image Edit Standard",
    operation: "image-to-image",
    outputKind: "image",
    maximumEstimatedCostUsd: 0.18,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "seedImage", type: "media", required: true },
      { name: "strength", type: "number", default: 0.8, minimum: 0, maximum: 1 },
    ],
  },
  {
    id: "heis-video-text-standard",
    provider: "runware",
    providerModelId: "google:3@3",
    displayName: "Heis Text to Video Standard",
    operation: "text-to-video",
    outputKind: "video",
    maximumEstimatedCostUsd: 5,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "duration", type: "number", default: 5, minimum: 4, maximum: 10 },
      { name: "aspectRatio", type: "enum", default: "16:9", options: ["16:9", "9:16", "1:1"] },
    ],
  },
  {
    id: "heis-video-standard",
    provider: "runware",
    providerModelId: "runway:1@1",
    displayName: "Heis Video Standard",
    operation: "image-to-video",
    outputKind: "video",
    maximumEstimatedCostUsd: 1.5,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "media", required: true },
      { name: "duration", type: "number", default: 5, minimum: 5, maximum: 10 },
    ],
  },
  {
    id: "heis-video-transform",
    provider: "runware",
    providerModelId: "luma:ray@3.2",
    displayName: "Heis Video Transform",
    operation: "video-to-video",
    outputKind: "video",
    maximumEstimatedCostUsd: 2,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "media", required: true },
      { name: "resolution", type: "enum", default: "720p", options: ["720p"] },
    ],
  },
  {
    id: "heis-marketing-video",
    provider: "runware",
    providerModelId: "alibaba:wan@3.0",
    displayName: "Heis Marketing Video",
    operation: "reference-to-video",
    outputKind: "video",
    maximumEstimatedCostUsd: 3,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "object", required: true },
      { name: "width", type: "number", required: true },
      { name: "height", type: "number", required: true },
      { name: "duration", type: "number", default: 5, minimum: 4, maximum: 15 },
    ],
  },
  {
    id: "heis-motion-control",
    provider: "runware",
    providerModelId: "bytedance:seedance@2.5",
    displayName: "Heis Motion Control",
    operation: "motion-control",
    outputKind: "video",
    maximumEstimatedCostUsd: 9,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "inputs", type: "object", required: true },
      { name: "duration", type: "number", default: 5, minimum: 4, maximum: 30 },
      { name: "settings", type: "object" },
      { name: "seed", type: "number" },
    ],
  },
  {
    id: "heis-lipsync-video",
    provider: "runware",
    providerModelId: "sync:lipsync-2@1",
    displayName: "Heis Video Lip Sync",
    operation: "lip-sync",
    outputKind: "video",
    maximumEstimatedCostUsd: 5,
    enabled: true,
    parameters: [
      { name: "inputs", type: "object", required: true },
      { name: "providerSettings", type: "object", required: true },
    ],
  },
  {
    id: "heis-lipsync-image",
    provider: "runware",
    providerModelId: "creatify:aurora@fast",
    displayName: "Heis Portrait Lip Sync",
    operation: "lip-sync",
    outputKind: "video",
    maximumEstimatedCostUsd: 2,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string" },
      { name: "inputs", type: "object", required: true },
    ],
  },
  {
    id: "heis-speech-standard",
    provider: "runware",
    providerModelId: "minimax:speech@2.8",
    displayName: "Heis Speech Standard",
    operation: "text-to-speech",
    outputKind: "audio",
    maximumEstimatedCostUsd: 2,
    enabled: true,
    parameters: [
      { name: "speech", type: "object", required: true },
    ],
  },
  {
    id: "heis-music-standard",
    provider: "runware",
    providerModelId: "minimax:music@2.6",
    displayName: "Heis Music Standard",
    operation: "text-to-music",
    outputKind: "audio",
    maximumEstimatedCostUsd: 0.5,
    enabled: true,
    parameters: [
      { name: "positivePrompt", type: "string", required: true },
      { name: "settings", type: "object" },
    ],
  },
];

export function getCapability(id: string): ModelCapability | undefined {
  return STARTER_RUNWARE_CATALOG.find((capability) => capability.id === id);
}
