# Requires fonttools and brotli in a Python environment.
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
root=Path(__file__).resolve().parents[1] / 'public' / 'brand';root.mkdir(exist_ok=True)
f=TTFont(str(root.parent/'fonts/dm-sans-latin.woff2'));f=instantiateVariableFont(f,{'wght':560},inplace=False);gs=f.getGlyphSet();cmap=f.getBestCmap();paths=[];x=0
for ch in 'heis':
 name=cmap[ord(ch)];pen=SVGPathPen(gs);gs[name].draw(pen);paths.append(f'<path transform="translate({x} 0)" d="{pen.getCommands()}"/>');x+=f['hmtx'][name][0]-25
word='<g transform="translate(0 76) scale(.1 -.1)">'+''.join(paths)+'</g>'
mark='M16 12H32V44L64 32V12H80L88 20V80L80 88H64V56L32 68V88H16L8 80V20Z'
def svg(name,w,h,body,label):
 (root/name).write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" role="img" aria-label="{label}">{body}</svg>\n')
for name,color in [('crimson','#ac2430'),('ivory','#f5eee6'),('black','#101113')]:
 svg(f'heis-symbol-{name}.svg',96,100,f'<path fill="{color}" d="{mark}"/>','Heis sculpted H')
 svg(f'heis-wordmark-{name}.svg',round(x*.1+6),100,f'<g fill="{color}">{word}</g>','heis')
 svg(f'heis-lockup-{name}.svg',round(x*.1+134),100,f'<path fill="{color}" d="{mark}"/><g transform="translate(128 0)" fill="{color}">{word}</g>','Heis')
svg('heis-lockup.svg',round(x*.1+134),100,f'<path fill="#ac2430" d="{mark}"/><g transform="translate(128 0)" fill="#f5eee6">{word}</g>','Heis')
svg('heis-app-icon.svg',512,512,f'<rect width="512" height="512" rx="112" fill="#101113"/><g transform="translate(88 81) scale(3.5)"><path fill="#ac2430" d="{mark}"/></g>','Heis app icon')
svg('heis-app-icon-crimson.svg',512,512,f'<rect width="512" height="512" rx="112" fill="#ac2430"/><g transform="translate(88 81) scale(3.5)"><path fill="#f5eee6" d="{mark}"/></g>','Heis app icon in crimson')
(root/'preview.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><title>Heis | Identity</title><style>
@font-face{font-family:DM;src:url('../fonts/dm-sans-latin.woff2')}*{box-sizing:border-box}body{margin:0;background:#101113;color:#f5eee6;font:14px DM,sans-serif}.sheet{width:1440px;padding:52px 64px 40px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #ffffff20;padding-bottom:24px}header strong{font-size:18px;font-weight:500}small{font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:#aaa4a1}.hero{height:450px;display:grid;grid-template-columns:1.5fr 1fr;align-items:center;gap:96px}.hero-logo{width:460px;max-height:155px}.hero p{color:#a7a1a0;font-size:16px;margin-top:38px;line-height:1.6;max-width:420px}.hero-icon{width:240px;justify-self:center;filter:drop-shadow(0 24px 50px #0004)}.cards{display:grid;grid-template-columns:1fr 1fr 1fr;gap:20px}.card{height:244px;padding:26px;display:flex;flex-direction:column;justify-content:space-between;border-radius:12px;border:1px solid #ffffff16}.ivory{background:#f5eee6;color:#101113}.red{background:#ac2430}.card>img{height:65px;max-width:260px;align-self:center;margin:auto}.ivory small{color:#706962}.red small{color:#f5eee6b3}.sizes{display:flex;align-items:end;gap:25px;margin:auto}.sizes img{display:block}.size{text-align:center}.size span{display:block;font-size:10px;color:#aaa4a1;margin-top:12px}.footer{display:flex;justify-content:space-between;align-items:center;margin-top:36px;padding-top:24px;border-top:1px solid #ffffff20}.palette{display:flex;gap:24px;color:#aaa4a1;font-size:12px}.swatch{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:8px}.domain{font-size:20px;letter-spacing:-.5px}.caption{font-size:12px;color:#aaa4a1;margin-top:6px}
</style><div class="sheet"><header><strong>heis / visual identity</strong><small>Sculpted H · 01</small></header><section class="hero"><div><img class="hero-logo" src="heis-lockup.svg"/><p>A single cut. A connected form.<br>A mark for a complete creative workspace.</p></div><img class="hero-icon" src="heis-app-icon-crimson.svg"/></section><section class="cards"><div class="card ivory"><small>On warm ivory</small><img src="heis-lockup-black.svg"/><span>Clear in one color.</span></div><div class="card red"><small>On deep crimson</small><img src="heis-lockup-ivory.svg"/><span>Color carries the identity.</span></div><div class="card"><small>Small by design</small><div class="sizes"><div class="size"><img src="heis-symbol-ivory.svg" width="16"/><span>16</span></div><div class="size"><img src="heis-symbol-ivory.svg" width="24"/><span>24</span></div><div class="size"><img src="heis-symbol-ivory.svg" width="32"/><span>32</span></div><div class="size"><img src="heis-symbol-ivory.svg" width="48"/><span>48</span></div><div class="size"><img src="heis-symbol-ivory.svg" width="64"/><span>64</span></div></div><span>App icon, toolbar, and favicon.</span></div></section><div class="footer"><div><div class="domain">heis.studio</div><div class="caption">Proposed web address</div></div><div class="palette"><span><i class="swatch" style="background:#ac2430"></i>Crimson / AC2430</span><span><i class="swatch" style="background:#f5eee6"></i>Ivory / F5EEE6</span><span><i class="swatch" style="background:#292a2e"></i>Charcoal / 101113</span></div></div></div></html>''')
