"use client";
import {useEffect,useState} from "react";
import {getBrowserClient} from "@/lib/supabase-browser";
export default function StoragePanel({onChange}:{onChange:()=>Promise<void>}) {
 const [files,setFiles]=useState<any[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 async function headers(){const {data}=await getBrowserClient().auth.getSession();return {Authorization:`Bearer ${data.session?.access_token}`,"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()};}
 async function refresh(){const response=await fetch('/v1/storage',{headers:await headers()});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??'Could not load storage');setFiles(body.files);}
 useEffect(()=>{void refresh().catch(error=>setError(error.message));},[]);
 async function upload(file?:File){if(!file)return;setBusy(true);setError("");try{const response=await fetch('/v1/uploads',{method:'POST',headers:await headers(),body:JSON.stringify({fileName:file.name,contentType:file.type,sizeBytes:file.size})});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??'Upload failed');const sent=await fetch(body.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!sent.ok)throw new Error('Upload could not finish. The reserved space will expire automatically.');await refresh();await onChange();}catch(error){setError(error instanceof Error?error.message:'Upload failed');}finally{setBusy(false);}}
 async function remove(file:any){setBusy(true);setError("");try{const response=await fetch('/v1/storage',{method:'DELETE',headers:await headers(),body:JSON.stringify({id:file.id,kind:file.kind})});if(!response.ok){const body=await response.json();throw new Error(body.error?.message??'Could not delete file');}await refresh();await onChange();}catch(error){setError(error instanceof Error?error.message:'Could not delete file');}finally{setBusy(false);}}
 return <section className="card"><h2>Cloud files</h2><p className="muted">Media is retained for up to 30 days. Download anything you want to keep. Maximum file size: 500 MB.</p><label>Upload media <input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime,audio/mpeg,audio/wav" onChange={event=>void upload(event.target.files?.[0])}/></label>{error&&<p role="alert">{error}</p>}<ul>{files.map(file=><li key={file.id}><a href={file.url}>Download {file.kind} · {(file.size_bytes/1024**2).toFixed(1)} MB</a> <button disabled={busy} onClick={()=>void remove(file)}>Delete cloud copy</button></li>)}</ul>{!files.length&&<p>No cloud files yet.</p>}</section>;
}
